DEB [20230518-16:28:08.538] thr=1   paramiko.transport: starting thread (client mode): 0xcd5ea460
DEB [20230518-16:28:08.539] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_3.1.0
ERR [20230518-16:28:08.809] thr=1   paramiko.transport: Exception (client): Error reading SSH protocol banner
ERR [20230518-16:28:08.814] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20230518-16:28:08.814] thr=1   paramiko.transport:   File "C:\Users\vlada\AppData\Local\python\mu\mu_venv-38-20230506-231228\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
ERR [20230518-16:28:08.815] thr=1   paramiko.transport:     buf = self.packetizer.readline(timeout)
ERR [20230518-16:28:08.815] thr=1   paramiko.transport:   File "C:\Users\vlada\AppData\Local\python\mu\mu_venv-38-20230506-231228\lib\site-packages\paramiko\packet.py", line 374, in readline
ERR [20230518-16:28:08.815] thr=1   paramiko.transport:     buf += self._read_timeout(timeout)
ERR [20230518-16:28:08.816] thr=1   paramiko.transport:   File "C:\Users\vlada\AppData\Local\python\mu\mu_venv-38-20230506-231228\lib\site-packages\paramiko\packet.py", line 603, in _read_timeout
ERR [20230518-16:28:08.816] thr=1   paramiko.transport:     raise EOFError()
ERR [20230518-16:28:08.816] thr=1   paramiko.transport: EOFError
ERR [20230518-16:28:08.816] thr=1   paramiko.transport: 
ERR [20230518-16:28:08.816] thr=1   paramiko.transport: During handling of the above exception, another exception occurred:
ERR [20230518-16:28:08.816] thr=1   paramiko.transport: 
ERR [20230518-16:28:08.817] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20230518-16:28:08.817] thr=1   paramiko.transport:   File "C:\Users\vlada\AppData\Local\python\mu\mu_venv-38-20230506-231228\lib\site-packages\paramiko\transport.py", line 2093, in run
ERR [20230518-16:28:08.817] thr=1   paramiko.transport:     self._check_banner()
ERR [20230518-16:28:08.817] thr=1   paramiko.transport:   File "C:\Users\vlada\AppData\Local\python\mu\mu_venv-38-20230506-231228\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
ERR [20230518-16:28:08.817] thr=1   paramiko.transport:     raise SSHException(
ERR [20230518-16:28:08.817] thr=1   paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERR [20230518-16:28:08.817] thr=1   paramiko.transport: 
DEB [20230518-16:39:49.501] thr=1   paramiko.transport: starting thread (client mode): 0x8f44370
DEB [20230518-16:39:49.502] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_3.1.0
ERR [20230518-16:39:49.766] thr=1   paramiko.transport: Exception (client): Error reading SSH protocol banner
ERR [20230518-16:39:49.769] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20230518-16:39:49.769] thr=1   paramiko.transport:   File "C:\Users\vlada\AppData\Local\python\mu\mu_venv-38-20230506-231228\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
ERR [20230518-16:39:49.769] thr=1   paramiko.transport:     buf = self.packetizer.readline(timeout)
ERR [20230518-16:39:49.770] thr=1   paramiko.transport:   File "C:\Users\vlada\AppData\Local\python\mu\mu_venv-38-20230506-231228\lib\site-packages\paramiko\packet.py", line 374, in readline
ERR [20230518-16:39:49.770] thr=1   paramiko.transport:     buf += self._read_timeout(timeout)
ERR [20230518-16:39:49.770] thr=1   paramiko.transport:   File "C:\Users\vlada\AppData\Local\python\mu\mu_venv-38-20230506-231228\lib\site-packages\paramiko\packet.py", line 603, in _read_timeout
ERR [20230518-16:39:49.770] thr=1   paramiko.transport:     raise EOFError()
ERR [20230518-16:39:49.770] thr=1   paramiko.transport: EOFError
ERR [20230518-16:39:49.770] thr=1   paramiko.transport: 
ERR [20230518-16:39:49.770] thr=1   paramiko.transport: During handling of the above exception, another exception occurred:
ERR [20230518-16:39:49.770] thr=1   paramiko.transport: 
ERR [20230518-16:39:49.770] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20230518-16:39:49.771] thr=1   paramiko.transport:   File "C:\Users\vlada\AppData\Local\python\mu\mu_venv-38-20230506-231228\lib\site-packages\paramiko\transport.py", line 2093, in run
ERR [20230518-16:39:49.771] thr=1   paramiko.transport:     self._check_banner()
ERR [20230518-16:39:49.771] thr=1   paramiko.transport:   File "C:\Users\vlada\AppData\Local\python\mu\mu_venv-38-20230506-231228\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
ERR [20230518-16:39:49.771] thr=1   paramiko.transport:     raise SSHException(
ERR [20230518-16:39:49.771] thr=1   paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERR [20230518-16:39:49.772] thr=1   paramiko.transport: 
